// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvmTsx4BWmXrv1CjanMRFxytdbxTQOKVI',
    appId: '1:919862981387:web:a71310c49d3e7a7bc1e80e',
    messagingSenderId: '919862981387',
    projectId: 'cliniqflow-cd4a7',
    authDomain: 'cliniqflow-cd4a7.firebaseapp.com',
    storageBucket: 'cliniqflow-cd4a7.firebasestorage.app',
    measurementId: 'G-4DFN5XKJ59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgDmRPDabdpGzDrWn62Z71CNhx7830gG8',
    appId: '1:919862981387:android:bf5fd2fa1f6e4c86c1e80e',
    messagingSenderId: '919862981387',
    projectId: 'cliniqflow-cd4a7',
    storageBucket: 'cliniqflow-cd4a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeOk6b1nYVhvZiMjSeEndP5NePQEd-lto',
    appId: '1:919862981387:ios:04e87dad523ba5b7c1e80e',
    messagingSenderId: '919862981387',
    projectId: 'cliniqflow-cd4a7',
    storageBucket: 'cliniqflow-cd4a7.firebasestorage.app',
    iosBundleId: 'com.example.cliniqflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeOk6b1nYVhvZiMjSeEndP5NePQEd-lto',
    appId: '1:919862981387:ios:04e87dad523ba5b7c1e80e',
    messagingSenderId: '919862981387',
    projectId: 'cliniqflow-cd4a7',
    storageBucket: 'cliniqflow-cd4a7.firebasestorage.app',
    iosBundleId: 'com.example.cliniqflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvmTsx4BWmXrv1CjanMRFxytdbxTQOKVI',
    appId: '1:919862981387:web:fa5045673eab19bcc1e80e',
    messagingSenderId: '919862981387',
    projectId: 'cliniqflow-cd4a7',
    authDomain: 'cliniqflow-cd4a7.firebaseapp.com',
    storageBucket: 'cliniqflow-cd4a7.firebasestorage.app',
    measurementId: 'G-ML5QDCWDRD',
  );

}